Repository TheJose24/EuphonyApp-Backend, pull requests merged in 2024-11, with the labels that each got.

#23 refactor: Refactorizacion de manejo de exepciones personalizadas
  src/main/java/com/euphony/streaming/exception/HttpStatusProvider.java
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/UserCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/UserDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/UserNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/UserUpdateException.java
Labels: refactor

#26 feat: Implementación de API para gestión de playlists (issue #25)
  src/main/java/com/euphony/streaming/controller/PlaylistController.java
  src/main/java/com/euphony/streaming/dto/request/PlaylistRequestDTO.java
  src/main/java/com/euphony/streaming/dto/response/PlaylistResponseDTO.java
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/PlaylistCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/PlaylistDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/PlaylistNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/PlaylistUpdateException.java
  src/main/java/com/euphony/streaming/service/implementation/PlaylistServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IPlaylistService.java
Labels: enhancement

#28 refactor: Ordenar las clases de excepcion personalizadas en carpetas
  src/main/java/com/euphony/streaming/controller/UserController.java
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/playlist/PlaylistCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/playlist/PlaylistDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/playlist/PlaylistNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/playlist/PlaylistUpdateException.java
  src/main/java/com/euphony/streaming/exception/custom/user/UserCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/user/UserDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/user/UserNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/user/UserUpdateException.java
  src/main/java/com/euphony/streaming/listener/UserProfileListener.java
  src/main/java/com/euphony/streaming/service/implementation/PlaylistServiceImpl.java
  src/main/java/com/euphony/streaming/service/implementation/ProfileUserServiceImpl.java
  src/main/java/com/euphony/streaming/service/implementation/UserServiceImpl.java
Labels: refactor

#30 feat: Implementar gestión de géneros musicales (Issue #29)
  src/main/java/com/euphony/streaming/controller/GenreController.java
  src/main/java/com/euphony/streaming/controller/PlaylistController.java
  src/main/java/com/euphony/streaming/dto/request/GenreRequestDTO.java
  src/main/java/com/euphony/streaming/dto/response/GenreResponseDTO.java
  src/main/java/com/euphony/streaming/exception/custom/genre/GenreCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/genre/GenreDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/genre/GenreNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/genre/GenreUpdateException.java
  src/main/java/com/euphony/streaming/repository/GeneroRepository.java
  src/main/java/com/euphony/streaming/service/implementation/GenreServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IGenreService.java
Labels: enhancement

#32 feat: Implementar gestión de artistas (Issue #31)
  src/main/java/com/euphony/streaming/controller/ArtistController.java
  src/main/java/com/euphony/streaming/dto/request/ArtistRequestDTO.java
  src/main/java/com/euphony/streaming/dto/response/ArtistResponseDTO.java
  src/main/java/com/euphony/streaming/entity/ArtistaEntity.java
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/artist/ArtistCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/artist/ArtistDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/artist/ArtistNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/artist/ArtistUpdateException.java
  src/main/java/com/euphony/streaming/repository/ArtistaRepository.java
  src/main/java/com/euphony/streaming/service/implementation/ArtistServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IArtistService.java
Labels: enhancement

#34 feat: implementar funcionalidad de seguimiento de artistas (Issue #33)
  src/main/java/com/euphony/streaming/controller/FollowersController.java
  src/main/java/com/euphony/streaming/dto/request/FollowersArtistRequestDTO.java
  src/main/java/com/euphony/streaming/dto/response/FollowersArtistResponseDTO.java
  src/main/java/com/euphony/streaming/entity/SeguidoresArtistaEntity.java
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/follow/FollowAlreadyExistsException.java
  src/main/java/com/euphony/streaming/exception/custom/follow/FollowBadRequestException.java
  src/main/java/com/euphony/streaming/exception/custom/follow/FollowNotFoundException.java
  src/main/java/com/euphony/streaming/repository/SeguidoresArtistaRepository.java
  src/main/java/com/euphony/streaming/service/implementation/FollowersServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IFollowersService.java
Labels: enhancement

#35 docs: modificar las respuestas en follow y unfollow
  src/main/java/com/euphony/streaming/controller/FollowersController.java
Labels: enhancement

#37 feature/planes de suspcripcion (issue #36)
  src/main/java/com/euphony/streaming/controller/PlanesSuscripcionController.java
  src/main/java/com/euphony/streaming/dto/request/PlanesSuscripcionRequestDTO.java
  src/main/java/com/euphony/streaming/dto/response/PlanesSuscripcionResponseDTO.java
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/subscription/SubscriptionCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/subscription/SubscriptionDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/subscription/SubscriptionNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/subscription/SubscriptionUpdateException.java
  src/main/java/com/euphony/streaming/service/implementation/PlanesSuscripcionServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IPlanesSuscripcionService.java
Labels: enhancement

#39 feat: implementar servicio automatico de verificacion de artistas (Issue #38)
  src/main/java/com/euphony/streaming/StreamingApplication.java
  src/main/java/com/euphony/streaming/entity/ArtistaEntity.java
  src/main/java/com/euphony/streaming/entity/NotificacionesArtistaEntity.java
  src/main/java/com/euphony/streaming/entity/NotificacionesUsuarioEntity.java
  src/main/java/com/euphony/streaming/entity/SeguidoresArtistaEntity.java
  src/main/java/com/euphony/streaming/event/ArtistVerificationEvent.java
  src/main/java/com/euphony/streaming/listener/ArtistVerificationListener.java
  src/main/java/com/euphony/streaming/publisher/ArtistVerificationPublisher.java
  src/main/java/com/euphony/streaming/repository/ArtistaRepository.java
  src/main/java/com/euphony/streaming/repository/NotificacionesArtistaRepository.java
  src/main/java/com/euphony/streaming/repository/NotificacionesRepository.java
  src/main/java/com/euphony/streaming/repository/NotificacionesUsuarioRepository.java
  src/main/java/com/euphony/streaming/repository/SeguidoresArtistaRepository.java
  src/main/java/com/euphony/streaming/service/implementation/AutomaticArtistVerificationServiceImpl.java
  src/main/java/com/euphony/streaming/service/implementation/FollowersServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IAutomaticArtistVerificationService.java
  src/main/java/com/euphony/streaming/util/ArtistFollowerCount.java
  src/main/resources/db/migration/V4__renombrar_notificaciones_y_agregar_titulo_y_crear_notificaciones_usuario.sql
  src/main/resources/db/migration/V5__agregar_verificacion_artista.sql
  src/test/java/com/euphony/streaming/service/AutomaticArtistVerificationServiceImplTest.java
Labels: enhancement

#41 fix: Correccion del método update y se renombro la carpeta y clases de excepciones
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/subcriptionplans/SubscriptionPlansCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/subcriptionplans/SubscriptionPlansDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/subcriptionplans/SubscriptionPlansNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/subcriptionplans/SubscriptionPlansUpdateException.java
  src/main/java/com/euphony/streaming/service/implementation/PlanesSuscripcionServiceImpl.java
Labels: bug

#43 feat: implementar servicio de almacenamiento de archivos (Issue #42)
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/storage/FileStorageException.java
  src/main/java/com/euphony/streaming/service/implementation/FileStorageServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IFileStorageService.java
  src/main/resources/application.properties
  src/test/java/com/euphony/streaming/service/FileStorageServiceImplTest.java
Labels: enhancement

#44 refactor: generar nombres unicos con nombre original y timestamp
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/service/implementation/FileStorageServiceImpl.java
Labels: refactor

#46 refactor: mejoras en FileStorageServiceImpl con estructura y manejo de errores optimizados
  src/main/java/com/euphony/streaming/service/implementation/FileStorageServiceImpl.java
  src/main/resources/application.properties
Labels: refactor

#48 feat: implementar gestion de álbumes (Issue #47)
  src/main/java/com/euphony/streaming/controller/AlbumController.java
  src/main/java/com/euphony/streaming/dto/request/AlbumRequestDTO.java
  src/main/java/com/euphony/streaming/dto/response/AlbumResponseDTO.java
  src/main/java/com/euphony/streaming/entity/AlbumEntity.java
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/album/AlbumCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/album/AlbumDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/album/AlbumNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/album/AlbumOperationException.java
  src/main/java/com/euphony/streaming/exception/custom/album/AlbumStorageException.java
  src/main/java/com/euphony/streaming/exception/custom/album/AlbumUpdateException.java
  src/main/java/com/euphony/streaming/exception/custom/album/AlbumValidationException.java
  src/main/java/com/euphony/streaming/repository/AlbumRepository.java
  src/main/java/com/euphony/streaming/service/implementation/AlbumServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IAlbumService.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V6__agregar_auditoria_album.sql
  uploads/images/default_cover_art.png
Labels: enhancement

#50 feat: implementar sistema de gestión de canciones (Issue #49)
  pom.xml
  src/main/java/com/euphony/streaming/controller/SongController.java
  src/main/java/com/euphony/streaming/dto/request/SongRequestDTO.java
  src/main/java/com/euphony/streaming/dto/response/SongMetadataResponseDTO.java
  src/main/java/com/euphony/streaming/dto/response/SongResponseDTO.java
  src/main/java/com/euphony/streaming/entity/CancionEntity.java
  src/main/java/com/euphony/streaming/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/euphony/streaming/exception/custom/metadata/InvalidMetadataException.java
  src/main/java/com/euphony/streaming/exception/custom/metadata/MetadataProcessingException.java
  src/main/java/com/euphony/streaming/exception/custom/song/SongCreationException.java
  src/main/java/com/euphony/streaming/exception/custom/song/SongDeletionException.java
  src/main/java/com/euphony/streaming/exception/custom/song/SongNotFoundException.java
  src/main/java/com/euphony/streaming/exception/custom/song/SongUpdateException.java
  src/main/java/com/euphony/streaming/repository/CancionGeneroRepository.java
  src/main/java/com/euphony/streaming/service/implementation/FileStorageServiceImpl.java
  src/main/java/com/euphony/streaming/service/implementation/SongMetadataServiceImpl.java
  src/main/java/com/euphony/streaming/service/implementation/SongServiceImpl.java
  src/main/java/com/euphony/streaming/service/interfaces/IFileStorageService.java
  src/main/java/com/euphony/streaming/service/interfaces/ISongMetadataService.java
  src/main/java/com/euphony/streaming/service/interfaces/ISongService.java
  src/main/resources/db/migration/V7__arreglar_tipos_de_datos_cancion.sql
Labels: enhancement

#52 feat: integracion servicios de monitoreo (Issue #51)
  .gitignore
  build.ps1
  pom.xml
  src/main/java/com/euphony/streaming/security/config/SecurityConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: enhancement
